version: '3.4'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api:
    build:
      context: .
    container_name: api
    hostname: api
    ports:
      - 80:3000
volumes:
  db_data: {}
